version: '3.8'

services:
  # PostgreSQL
  db:
    image: postgres:16-bookworm
    container_name: my_postgres
    env_file:
      - environments/.env.postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  # FastAPI
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: sf_fastapi_backend
    env_file:
      - environments/.env.fastapi
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app

volumes:
  postgres_data:
